jwt:
  secret: mysecretkey
#  毫秒为单位，注意1秒等于1000毫秒，而不是60进制，设置为1天
  expiration: 86400000
server:
  port: 8081
spring:
  mail:
    # 下面这个是QQ邮箱host ， 企业邮箱 : smtp.exmail.qq.com
    host: smtp.qq.com
    # tencent mail port  这个是固定的
    port: 465
    # 你的QQ邮箱
    username: 3434549571@qq.com
    # 进入邮箱配置后得到的授权码,更改密码后会失效，请注意
    password: gsqcjdjnhoincjei
    test-connection: true
    properties:
      mail:
        smtp:
          ssl:
            enable: true
  http:
    encoding:
      force: true
      charset: UTF-8
    messages:
      encoding: UTF-8

  redis:
    database: 0
    host: 124.221.7.201
    port: 6379
    timeout: 5000
    password: 17628887613Hyw.

  servlet:
    multipart:
      location: /home/img/add
      enabled: true
      max-file-size: 5MB  #设置上传文件最大不超过5mb
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://124.221.7.201:3306/explor_gastro?serverTimezone=GMT%2B8
    username: aroot
    password: aKwRhwEEKY4PJ28N
  mvc:
    static-path-pattern: /static/**
  thymeleaf:
    prefix: classpath:/templates/
mybatis-plus:
  mapper-locations: classpath*:mapper/*Mapper.xml
  type-aliases-package: com.buy_customers.demo.model
  #  加入日志功能
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
upload: D:\logger

# springdoc-openapi configuration
# To get help follow the link to get more information
# https://doc.xiaominfo.com/docs/quick-start
# springdoc-openapi 配置
springdoc:
  # Swagger-UI 路径配置
  swagger-ui:
    path: /swagger-ui.html
    # 标签排序规则
    tags-sorter: alpha
    # 操作排序规则
    operations-sorter: alpha
  # API 文档路径配置
  api-docs:
    path: /v3/api-docs
  # 接口分组配置
  group-configs:
    # 默认分组
    - group: 'default'
      # 匹配所有路径
      paths-to-match: '/**'
      # 扫描控制器包
      packages-to-scan: com.buy_customers.controller
knife4j:
  enable: true
logging:
  config: classpath:log4j2.xml
  level:
    root: INFO
    javax.activation: info
    org.apache.catalina: INFO
    org.apache.commons.beanutils.converters: INFO
    org.apache.coyote.http11.Http11Processor: INFO
    org.apache.http: INFO
    org.apache.tomcat: INFO
    org.springframework: INFO
    com.chinamobile.cmss.bdpaas.resource.monitor: DEBUG