jwt:
  secret: mysecretkey
#  毫秒为单位，注意1秒等于1000毫秒，而不是60进制，设置为1天
  expiration: 86400000
server:
  servlet:
    encoding:
      charset: UTF-8
      force: true
  port: 8081
spring:
  #  elasticsearch:
  #    rest:
  #      uris: 172.25.168.187:9200
  #      connection-timeout: 1s
  #      read-timeout: 30s
  mail:
    # 下面这个是QQ邮箱host ， 企业邮箱 : smtp.exmail.qq.com
    host: smtp.qq.com
    # tencent mail port  这个是固定的
    port: 465
    # 你的QQ邮箱
    username: 3434549571@qq.com
    # 进入邮箱配置后得到的授权码,更改密码后会失效，请注意
    password: gsqcjdjnhoincjei
    test-connection: true
    properties:
      mail:
        smtp:
          ssl:
            enable: true

  redis:
    database: 0
    host: 124.221.7.201
    port: 6379
    timeout: 5000
    password: 17628887613Hyw.

  servlet:
    multipart:
      location: /home/img/add
      enabled: true
      max-file-size: 5MB  #设置上传文件最大不超过5mb
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://124.221.7.201:3306/explor_gastro?serverTimezone=GMT%2B8&rewriteBatchedstatements=true
    username: aroot
    password: aKwRhwEEKY4PJ28N
  mvc:
    static-path-pattern: /static/**
  thymeleaf:
    prefix: classpath:/templates/
mybatis-plus:
  mapper-locations: classpath*:mapper/*Mapper.xml
  type-aliases-package: com.buy_customers.demo.model
  #  加入日志功能
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
upload: D:\logger

logging:
  config: classpath:log4j2.xml
  level:
    root: INFO
    javax.activation: info
    org.apache.catalina: INFO
    org.apache.commons.beanutils.converters: INFO
    org.apache.coyote.http11.Http11Processor: INFO
    org.apache.http: INFO
    org.apache.tomcat: INFO
    org.springframework: INFO
    com.chinamobile.cmss.bdpaas.resource.monitor: DEBUG

############## Sa-Token 配置 (文档: https://sa-token.cc) ##############
sa-token:
  # token 名称（同时也是 cookie 名称）
  token-name: satoken
  # token 有效期（单位：秒） 默认30天，-1 代表永久有效
  timeout: 604800
  # token 最低活跃频率（单位：秒），如果 token 超过此时间没有访问系统就会被冻结，默认-1 代表不限制，永不冻结
  active-timeout: -1
  # 是否允许同一账号多地同时登录 （为 true 时允许一起登录, 为 false 时新登录挤掉旧登录）
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个 token （为 true 时所有登录共用一个 token, 为 false 时每次登录新建一个 token）
  is-share: true
  # token 风格（默认可取值：uuid、simple-uuid、random-32、random-64、random-128、tik）
  token-style: uuid
  # 是否输出操作日志
  is-log: true
  sign:
    # API 接口签名秘钥 （随便乱摁几个字母即可）
    secret-key: skfjnANJjmvkAFSVBNvn

